version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_passwd
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  wordpress:
    image: wordpress:5.8
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_user_passwd
      WORDPRESS_DB_NAME: mysql_db
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
  db:
